# Generated by Django 6.0.5 on 2026-05-12 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proverb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Полный текст тувинской пословицы с пропуском (обозначьте пропуск как _____)', verbose_name='Текст пословицы')),
                ('missing_word', models.CharField(help_text='Слово, которое нужно вставить вместо пропуска', max_length=100, verbose_name='Пропущенное слово')),
                ('hint', models.TextField(blank=True, help_text='Необязательная подсказка для игроков', null=True, verbose_name='Подсказка')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время добавления пословицы', verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Пословица',
                'verbose_name_plural': 'Пословицы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_games', models.IntegerField(default=0, help_text='Общее количество завершённых игр', verbose_name='Всего игр')),
                ('wins', models.IntegerField(default=0, help_text='Количество игр с правильным ответом', verbose_name='Побед')),
                ('total_attempts', models.IntegerField(default=0, help_text='Суммарное количество всех попыток', verbose_name='Всего попыток')),
                ('best_score', models.IntegerField(default=0, help_text='Минимальное количество попыток в победной игре', verbose_name='Лучший счёт')),
                ('last_played', models.DateTimeField(auto_now=True, help_text='Дата и время последней игры', verbose_name='Последняя игра')),
                ('user', models.ForeignKey(help_text='Игрок', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Результат игры',
                'verbose_name_plural': 'Результаты игр',
                'ordering': ['-wins', 'total_attempts'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.IntegerField(default=0, help_text='Количество попыток ответа (максимум 3)', verbose_name='Попыток сделано')),
                ('is_correct', models.BooleanField(default=False, help_text='True если игрок дал правильный ответ', verbose_name='Угадано')),
                ('completed_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время завершения игры', verbose_name='Время завершения')),
                ('user', models.ForeignKey(help_text='Игрок, который проходит квест', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('proverb', models.ForeignKey(help_text='Пословица для отгадывания', on_delete=django.db.models.deletion.CASCADE, to='game.proverb', verbose_name='Пословица')),
            ],
            options={
                'verbose_name': 'Игровая сессия',
                'verbose_name_plural': 'Игровые сессии',
                'ordering': ['-completed_at'],
            },
        ),
    ]
